#!/usr/bin/env python3
"""Create a reproducible, project-specific multilingual research packet."""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path


def csv_items(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def safe_slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "research-packet"


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def write_csv(path: Path, headers: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as stream:
        csv.writer(stream).writerow(headers)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a multilingual regional research packet."
    )
    parser.add_argument("--project", required=True)
    parser.add_argument("--decision", required=True)
    parser.add_argument("--countries", required=True)
    parser.add_argument("--languages", required=True)
    parser.add_argument("--domains", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    output = Path(args.output).expanduser().resolve()
    if output.exists():
        raise SystemExit(f"Refusing to overwrite existing packet: {output}")

    countries = csv_items(args.countries)
    languages = csv_items(args.languages)
    domains = csv_items(args.domains)
    output.mkdir(parents=True)

    write_text(
        output / "README.md",
        f"# {args.project} regional research packet\n\n"
        f"Decision: {args.decision}\n\n"
        "This packet was generated by `china-frontier`. "
        "Do not claim a conclusion until the source ledger, repository audit, "
        "and evaluation plan identify its evidence status.\n",
    )
    write_text(
        output / "research-contract.md",
        "# Research Contract\n\n"
        f"- Project: {args.project}\n"
        f"- Decision: {args.decision}\n"
        f"- Countries: {', '.join(countries)}\n"
        f"- Languages/scripts: {', '.join(languages)}\n"
        f"- Domains: {', '.join(domains)}\n"
        "- Time boundary: TODO\n"
        "- Users/decision owners: TODO\n"
        "- Available data and rights: TODO\n"
        "- Compute and deployment constraints: TODO\n"
        "- Acceptance metrics: TODO\n"
        "- Failure criteria: TODO\n"
        "- Human-gated actions: TODO\n",
    )
    write_text(
        output / "query-bank.md",
        "# Query Bank\n\n"
        "For each query preserve the original language, English gloss, source "
        "engine/index, date, and reason for searching.\n\n"
        "## Required queries\n\n"
        + "\n".join(f"- [{country}] TODO native-language queries" for country in countries)
        + "\n\n## Domains\n\n"
        + "\n".join(f"- [{domain}] TODO capability gap and evidence needed" for domain in domains)
        + "\n",
    )
    write_text(
        output / "evaluation-plan.md",
        "# Evaluation Plan\n\n"
        "Define baselines and slices before candidate selection.\n\n"
        "- Task and prediction unit: TODO\n"
        "- Labels and proxy limitations: TODO\n"
        "- Group/time/country/language split: TODO\n"
        "- Per-language/script/domain metrics: TODO\n"
        "- Calibration and uncertainty: TODO\n"
        "- Rights, privacy, safety, and security tests: TODO\n"
        "- Translation/transliteration/terminology stress tests: TODO\n"
        "- Provider outage and stale-source tests: TODO\n"
        "- Adoption threshold and rollback: TODO\n",
    )
    write_text(
        output / "decision-log.md",
        "# Decision Log\n\n"
        "| Date | Decision | Evidence status | Source IDs | Local result | Consequence | Owner | Revisit trigger |\n"
        "|---|---|---|---|---|---|---|---|\n",
    )
    write_csv(
        output / "source-ledger.csv",
        [
            "source_id", "country", "language_script", "domain", "source_type",
            "original_title", "english_gloss", "url", "publication_or_commit_date",
            "claim", "mechanism", "assumptions", "data_labels", "evaluation_split",
            "reported_metrics", "rights", "evidence_status", "transferability",
            "decision", "notes",
        ],
    )
    write_csv(
        output / "repository-audit.csv",
        [
            "repository", "canonical_owner", "commit_sha", "commit_date",
            "native_docs_read", "code_license", "weights_license", "data_license",
            "service_terms", "tests_eval", "dynamic_code_network_surface",
            "reproduction_status", "transferable_mechanism", "adoption_status", "notes",
        ],
    )
    write_csv(
        output / "coverage-matrix.csv",
        ["country", "language_script", "domain", "papers", "official_sources",
         "repositories", "datasets", "standards_policy", "grey_literature",
         "design_change", "gap"],
    )
    print(f"Created research packet: {output}")
    print(f"Suggested slug: {safe_slug(args.project)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
